# Generated by Django 4.2.11 on 2025-06-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_message', models.TextField()),
                ('filled_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
