# Generated by Django 4.2.11 on 2025-06-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clientmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permitrequest',
            old_name='place',
            new_name='location',
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='subcounty',
            field=models.CharField(default='Kilifi North', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-06-17 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='ward',
            field=models.CharField(default='Mnarani', max_length=100),
            preserve_default=False,
        ),
    ]
