# Generated by Django 4.2.11 on 2025-06-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_place_permitrequest_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='subcounty',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='ward',
            field=models.CharField(max_length=50),
        ),
    ]
