# Generated by Django 4.2.11 on 2025-07-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_permitrequest_approved_alter_permitrequest_subcounty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
